// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVIwLhJYS6VQdJJIOmT24V9SjKhxh-L3Q',
    appId: '1:185052862302:web:6df04608979e0d7f6fa1cf',
    messagingSenderId: '185052862302',
    projectId: 'think-ninjas-a61bb',
    authDomain: 'think-ninjas-a61bb.firebaseapp.com',
    storageBucket: 'think-ninjas-a61bb.appspot.com',
    measurementId: 'G-C8PYNC7497',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATRDpw85Kso-vtJRxNHXv4XaOB_u62Ako',
    appId: '1:185052862302:android:86ba35086fb66c636fa1cf',
    messagingSenderId: '185052862302',
    projectId: 'think-ninjas-a61bb',
    storageBucket: 'think-ninjas-a61bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDERR8r0XJXYXBsf4-lF-t81MTrz-99jaA',
    appId: '1:185052862302:ios:5a295897b6ab5f8c6fa1cf',
    messagingSenderId: '185052862302',
    projectId: 'think-ninjas-a61bb',
    storageBucket: 'think-ninjas-a61bb.appspot.com',
    iosBundleId: 'com.example.thinkNinjaTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDERR8r0XJXYXBsf4-lF-t81MTrz-99jaA',
    appId: '1:185052862302:ios:21495351db433c8b6fa1cf',
    messagingSenderId: '185052862302',
    projectId: 'think-ninjas-a61bb',
    storageBucket: 'think-ninjas-a61bb.appspot.com',
    iosBundleId: 'com.example.thinkNinjaTest.RunnerTests',
  );
}
